version: '3'
services:
    creditrating:
        image: microcoffeeonkube-creditrating:1.0.0-SNAPSHOT
        ports:
            - "8083:8083"
            - "8446:8446"
        environment:
            # See application.properties for supported behaviors
            - CREDITRATING_SERVICE_BEHAVIOR=0
            - CREDITRATING_SERVICE_BEHAVIOR_DELAY=10
            