---
apiVersion: v1
kind: Pod
metadata:
  name: microcoffee
  labels:
    app: microcoffee
spec:
  containers:
    - name: creditrating
      image: microcoffeeonkube-creditrating:1.0.0-SNAPSHOT
      ports:
        - containerPort: 8083
          hostPort: 8083
        - containerPort: 8446
          hostPort: 8446
      env:
        - name: CREDITRATING_SERVICE_BEHAVIOR
          value: "0"
        - name: CREDITRATING_SERVICE_BEHAVIOR_FIXEDDELAY
          value: "10"
          