---
apiVersion: v1
kind: Pod
metadata:
  name: microcoffee
  labels:
    app: microcoffee
spec:
  containers:
    - name: order
      image: microcoffeeonkube-order:1.0.0-SNAPSHOT
      ports:
        - containerPort: 8082
          hostPort: 8082
        - containerPort: 8445
          hostPort: 8445
      env:
        - name: MICROCOFFEE_MONGODB_SERVICE_HOST
          value: "192.168.99.100"
        - name: MICROCOFFEE_MONGODB_SERVICE_PORT
          value: "27017"
    - name: mongodb
      image: mongo:3.4.8
      ports:
        - containerPort: 27017
          hostPort: 27017
        - containerPort: 28017
          hostPort: 28017
      volumeMounts:
        - name: mongodbdata
          mountPath: /data/db
  volumes:
    - name: mongodbdata
      hostPath:
        path: /mnt/sda1/data/mongodbdata
