---
apiVersion: v1
kind: Pod
metadata:
  name: microcoffee
  labels:
    app: microcoffee
spec:
  containers:
    - name: mongodb
      image: tutum/mongodb:3.2
      ports:
        - containerPort: 27017
          hostPort: 27017
        - containerPort: 28017
          hostPort: 28017
      volumeMounts:
        - name: mongodbdata
          mountPath: /data/db
      env:
        - name: AUTH
          value: "no"
  volumes:
    - name: mongodbdata
      hostPath:
        path: /mnt/sda1/data/mongodbdata
