---
apiVersion: v1
kind: Service
metadata:
  name: microcoffee-order
  labels:
    app: microcoffee
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      name: order-http
    - port: 8445
      targetPort: 8445
      name: order-https
  selector:
    app: microcoffee
    tier: frontend
  externalIPs:
    - 192.168.99.100
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: microcoffee-order
  labels:
    app: microcoffee
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microcoffee
        tier: frontend
    spec:
      containers:
        - name: order
          image: microcoffeeonkube-order:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8082
              name: order-http
            - containerPort: 8445
              name: order-https
