---
apiVersion: v1
kind: Service
metadata:
  name: microcoffee-gui
  labels:
    app: microcoffee
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 8080
      name: gui-http
    - port: 9443
      targetPort: 8443
      name: gui-https
  selector:
    app: microcoffee
    tier: frontend
  externalIPs:
    - 192.168.99.100
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: microcoffee-gui
  labels:
    app: microcoffee
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microcoffee
        tier: frontend
    spec:
      containers:
        - name: gui
          image: microcoffeeonkube-gui:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
              name: gui-http
            - containerPort: 8443
              name: gui-https
          env:
            - name: MICROCOFFEE_WEB_HOST
              value: "192.168.99.100"
            - name: MICROCOFFEE_WEB_PORT_LOCATION_HTTP
              value: "8081"
            - name: MICROCOFFEE_WEB_PORT_LOCATION_HTTPS
              value: "8444"
            - name: MICROCOFFEE_WEB_PORT_ORDER_HTTP
              value: "8082"
            - name: MICROCOFFEE_WEB_PORT_ORDER_HTTPS
              value: "8445"
